name: Check styling

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

permissions:
  contents: read

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Setup PHP
        uses: shivammathur/setup-php@2.40.0
        with:
          php-version: '8.4'
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Check PHP styling
        run: composer format -- --dry-run --diff
