name: Run Tests

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [8.2, 8.3, 8.4]
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: '11.*'
            testbench: '^9.0'
            pest: '^2.0'
            plugin: '^3.0'
            phpunit: '^10.5'
          - laravel: '12.*'
            php: 8.3
            testbench: '^10.0'
            pest: '^3.0'
            plugin: '^3.0'
            phpunit: '^11.5.3'
          - laravel: '12.*'
            php: 8.4
            testbench: '^10.0'
            pest: '^3.0'
            plugin: '^3.0'
            phpunit: '^11.5.3'

    name: PHP ${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require --dev "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "pestphp/pest:${{ matrix.pest }}" "pestphp/pest-plugin-laravel:${{ matrix.plugin }}" "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/pest
